[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
CUDATools = "9ec180c6-1c07-47c7-9e6e-ebefa4d1f6d0"
CUPTI = "9e67e8f6-ba02-4b6c-a7db-3b11ae1e7ab7"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
NVML = "611af6d1-644e-4c5d-bd58-854d7d1254b9"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
cuBLAS = "182d3088-87b7-4494-8cad-fc6afaa545bc"
cuFFT = "533571aa-0936-420e-b4be-9c66f5f626ca"
cuRAND = "20fd9a0b-12d5-4c2f-a8af-7c34e9e60431"
cuSOLVER = "887afef0-6a32-4de5-add4-7827692ba8fc"
cuSPARSE = "b26da814-b3bc-49ef-b0ee-c816305aa060"
cuTile = "0dea8319-8c4a-4662-a73d-20234d115b9a"

[sources]
CUDA = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main"}
CUDACore = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "CUDACore"}
CUDATools = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "CUDATools"}
CUPTI = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/cupti"}
NVML = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/nvml"}
cuBLAS = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/cublas"}
cuFFT = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/cufft"}
cuRAND = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/curand"}
cuSOLVER = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/cusolver"}
cuSPARSE = {url = "https://github.com/JuliaGPU/CUDA.jl", rev = "main", subdir = "lib/cusparse"}
cuTile = {path = ".."}

[compat]
CUDA = "6.2.1"
FFTW = "1.10.0"
NVTX = "1.0.3"
